'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const{STORES,validateURL,parseProduct}=require('./store-parsers.cjs');
function createCatalogService(dir,city='Воронеж'){
const file=path.join(dir,'catalog.json');
const TTL=6*60*60*1000;
let data={city,items:[],sources:[]},loaded=false,tail=Promise.resolve();
async function init(){if(loaded)return;try{const saved=JSON.parse(await fs.readFile(file,'utf8'));if(saved.city===city&&Array.isArray(saved.items)&&Array.isArray(saved.sources))data=saved}catch(e){if(e.code!=='ENOENT')console.error('Catalog cache could not be read')}loaded=true}
async function save(){await fs.mkdir(dir,{recursive:true});await fs.writeFile(file+'.tmp',JSON.stringify(data,null,2));await fs.rename(file+'.tmp',file)}
function serial(task){const run=tail.then(task);tail=run.catch(()=>{});return run}
async function fetchPage(url,product=true){let target=validateURL(url,product).url;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{for(let hops=0;hops<3;hops++){const r=await fetch(target,{signal:controller.signal,redirect:'manual',headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'NaNedelyuPrototype/1.0'}});if([301,302,303,307,308].includes(r.status)){const next=new URL(r.headers.get('location'),target).href;if(validateURL(next,product).store!==validateURL(target,product).store)throw Error('Магазин перенаправляет на другой источник.');target=next;continue}if(!r.ok)throw Error(r.status===401?"Источник требует авторизованный доступ к каталогу.":r.status===403?"Магазин ограничил автоматическую загрузку.":`Магазин временно не отдаёт карточку (HTTP ${r.status}).`);if(!/text\/html|application\/xhtml\+xml/.test(r.headers.get('content-type')||''))throw Error('Источник вернул не HTML-карточку.');let size=0;const chunks=[];for await(const c of r.body){size+=c.length;if(size>4*1024*1024){controller.abort();throw Error('Страница слишком велика.')}chunks.push(c)}return{html:Buffer.concat(chunks).toString('utf8'),url:target}}throw Error('Слишком много перенаправлений.')}catch(e){if(e.name==='AbortError'||e.name==='TimeoutError')throw Error('Магазин не ответил за 15 секунд.');throw e}finally{clearTimeout(timer)}}
function publicData(){return{...data,ttlHours:TTL/3600000,items:data.items.map(p=>{const stale=Date.now()-Date.parse(p.fetchedAt)>TTL||!Number.isFinite(Date.parse(p.fetchedAt));return{...p,stale,usable:p.usable&&!stale&&!p.refreshError}})}}
async function importItem(url,ingredient){await init();const parsedURL=validateURL(url);const cached=data.items.find(p=>p.requestedUrl===parsedURL.url&&p.ingredient===ingredient);if(cached&&Date.now()-Date.parse(cached.fetchedAt)<TTL&&!cached.refreshError)return publicData();const page=await fetchPage(parsedURL.url);const p=parseProduct(page.html,parsedURL.url,city);p.ingredient=ingredient;p.id=crypto.createHash('sha256').update(p.store+'|'+p.externalId+'|'+p.storeCode+'|'+ingredient).digest('hex').slice(0,24);data.items=data.items.filter(x=>x.id!==p.id);data.items.push(p);data.items=data.items.slice(-150);await save();return publicData()}
async function checkSources(){await init();for(const[key,s]of Object.entries(STORES)){const last=data.sources.find(x=>x.key===key);if(last&&Date.now()-Date.parse(last.checkedAt)<60000)continue;const result={key,name:s.name,checkedAt:new Date().toISOString(),status:'unavailable',message:''};try{const{html}=await fetchPage(s.home,false);if(/js-challenge-loader|servicepipe\.tech|captcha/i.test(html)&&!html.includes('__NUXT_DATA__'))throw Error('Сайт требует проверку браузера. Автоматический каталог не подключён.');result.status=key==='magnit'?'partial':'needs_adapter';result.message=key==='magnit'?'Карточки читаются. Цены выбранного города пока не подтверждены: проверяем фактический магазин.':'Страница доступна; региональный каталог и формат данных ещё не подключены.'}catch(e){result.message=e.message}data.sources=data.sources.filter(x=>x.key!==key);data.sources.push(result)}await save();return publicData()}
async function refresh(){await init();for(const p of [...data.items]){if(Date.now()-Date.parse(p.lastAttemptAt||p.fetchedAt)<60000)continue;try{const page=await fetchPage(p.requestedUrl),next=parseProduct(page.html,p.requestedUrl,city);Object.assign(p,next,{refreshError:null,lastAttemptAt:new Date().toISOString()});const i=data.items.findIndex(x=>x.id===p.id);data.items[i]=p}catch(e){const old=data.items.find(x=>x.id===p.id);old.refreshError=e.message;old.lastAttemptAt=new Date().toISOString()}}await save();return publicData()}
async function dispatch(method,route,body){return serial(async()=>{await init();if(method==='GET'&&route==='/api/catalog')return publicData();if(method!=='POST')throw Error('Метод не поддерживается.');if(route==='/api/catalog/import'){if(typeof body.url!=='string'||body.url.length>2000||typeof body.ingredient!=='string'||!/^[a-z]{2,20}$/.test(body.ingredient))throw Error('Проверьте ссылку и ингредиент.');return importItem(body.url,body.ingredient)}if(route==='/api/catalog/check')return checkSources();if(route==='/api/catalog/refresh')return refresh();if(route==='/api/catalog/delete'){data.items=data.items.filter(x=>x.id!==body.id);await save();return publicData()}throw Error('Неизвестный запрос.')})}
return {dispatch,fetchPage};}
const instances=new Map();function catalogFor(user){const key=user.id+':'+user.city.id;if(!instances.has(key))instances.set(key,createCatalogService(path.join(__dirname,'../.catalog-cache',user.id,String(user.city.id)),user.city.name));return instances.get(key)}
module.exports={createCatalogService,catalogFor};
