'use strict';
const GEO=process.env.MEAL_GEOCODING_URL||'https://geocoding-api.open-meteo.com/v1/search';
const OVERPASS=process.env.MEAL_OVERPASS_URL||'https://maps.mail.ru/osm/tools/overpass/api/interpreter';
const TILE=process.env.MEAL_TILE_URL||'https://tile.openstreetmap.org/{z}/{x}/{y}.png';
const cities=new Map(),requests=new Map(),areas=new Map();let nextGeoAt=0,nextMapAt=0;
async function json(url,options={}){const r=await fetch(url,{...options,headers:{'User-Agent':'NaNedelyuLocalPrototype/1.0',...options.headers},signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('Сервис карты временно недоступен. Попробуйте ещё раз.');const text=await r.text();if(text.length>3000000)throw Error('Слишком большой ответ карты.');return JSON.parse(text)}
async function searchCities(q){if(typeof q!=='string'||q.trim().length<2||q.length>100)throw Error('Введите название города — от 2 символов.');q=q.trim();const key=q.toLowerCase();if(requests.has(key))return {cities:requests.get(key),attribution:"Open-Meteo · GeoNames"};const now=Date.now();if(now<nextGeoAt)throw Error('Подождите секунду перед следующим поиском.');nextGeoAt=now+1100;const url=new URL(GEO);for(const[k,v]of Object.entries({name:q,count:10,language:'ru',countryCode:'RU',format:'json'}))url.searchParams.set(k,v);const j=await json(url);const result=(j.results||[]).filter(x=>x.country_code==='RU'&&String(x.feature_code).startsWith('PPL')).map(x=>({id:x.id,name:x.name,region:x.admin1||'',lat:x.latitude,lon:x.longitude}));result.forEach(x=>cities.set(x.id,x));requests.set(key,result);if(requests.size>100)requests.delete(requests.keys().next().value);return{cities:result,attribution:'Open-Meteo · GeoNames'}}
function distance(a,b){const rad=x=>x*Math.PI/180;const x=Math.sin(rad(b.lat-a.lat)/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(rad(b.lon-a.lon)/2)**2;return 6371000*2*Math.atan2(Math.sqrt(x),Math.sqrt(Math.max(0,1-x)))}
function chain(tags){const n=(tags.brand||'')+' '+(tags.name||'');if(/косметик|аптек|cosmetic/i.test(n))return null;if(/пят[её]рочк|pyaterochka/i.test(n))return 0;if(/магнит|magnit/i.test(n))return 1;if(/лент[аы]|lenta/i.test(n))return 2;if(/перекр[её]сток|perekrestok/i.test(n))return 3;if(/ашан|auchan/i.test(n))return 4;return null}
function normalizeStores(elements,point){const found=[];for(const e of elements){const t=e.tags||{},c=chain(t),lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon;if(c===null||!Number.isFinite(lat)||!Number.isFinite(lon)||!['supermarket','convenience'].includes(t.shop))continue;const item={id:e.type+'/'+e.id,chain:c,name:t.name||t.brand,lat,lon,address:[t['addr:street'],t['addr:housenumber']].filter(Boolean).join(', ')||'Адрес в карте не указан',hours:t.opening_hours||null,sourceUrl:'https://www.openstreetmap.org/'+e.type+'/'+e.id};item.distanceMeters=Math.round(distance(point,item));if(!found.some(x=>x.chain===c&&distance(x,item)<25))found.push(item)}return found.sort((a,b)=>a.distanceMeters-b.distanceMeters).slice(0,150)}
async function nearby(lat,lon){if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<-90||lat>90||lon<-180||lon>180)throw Error('Некорректная точка на карте.');const key=lat.toFixed(3)+','+lon.toFixed(3),cached=areas.get(key);if(cached&&Date.now()-cached.time<3600000)return{...cached.result,items:cached.result.items.map(s=>({...s,distanceMeters:Math.round(distance({lat,lon},s))})).sort((a,b)=>a.distanceMeters-b.distanceMeters)};
 if(Date.now()<nextMapAt)throw Error('Подождите несколько секунд перед новым поиском магазинов.');nextMapAt=Date.now()+3000;
 const query=`[out:json][timeout:15];nwr(around:5000,${lat},${lon})["shop"~"^(supermarket|convenience)$"];out center tags;`;
 const endpoint=new URL(OVERPASS);endpoint.searchParams.set('data',query);const raw=await json(endpoint);if(raw.remark)throw Error('Сервис карты не завершил поиск. Повторите позднее.');if(!Array.isArray(raw.elements))throw Error('Сервис карты вернул неизвестный ответ.');const result={items:normalizeStores(raw.elements,{lat,lon}),radiusMeters:5000,fetchedAt:new Date().toISOString(),attribution:'© OpenStreetMap contributors',tileUrl:TILE};areas.set(key,{time:Date.now(),result});if(areas.size>100)areas.delete(areas.keys().next().value);return result}
module.exports={searchCities,nearby,normalizeStores,distance,chain,knownCity:id=>cities.get(id),TILE};
