'use strict';
const STORES={pyaterochka:{name:'Пятёрочка',index:0,host:'5ka.ru',home:'https://5ka.ru/'},magnit:{name:'Магнит',index:1,host:'magnit.ru',home:'https://magnit.ru/'},lenta:{name:'Лента',index:2,host:'lenta.com',home:'https://lenta.com/catalog/'},perekrestok:{name:'Перекрёсток',index:3,host:'perekrestok.ru',home:'https://www.perekrestok.ru/cat'}};
function number(v){if(typeof v==='number')return Number.isFinite(v)?v:null;if(typeof v!=='string'||!/^\s*\d+(?:[.,]\d+)?\s*$/.test(v))return null;return Number(v.trim().replace(',','.'))}
function plain(v){return typeof v==='string'?v.replace(/<[^>]*>/g,'').trim().slice(0,600):''}
function validateURL(raw,product=true){let u;try{u=new URL(raw)}catch{throw Error('Нужна полная ссылка на товар магазина.')}
 const entry=Object.entries(STORES).find(([,s])=>[s.host,'www.'+s.host].includes(u.hostname));
 if(!entry||u.protocol!=='https:'||u.port||u.username||u.password)throw Error('Разрешены только HTTPS-ссылки Пятёрочки, Магнита, Ленты и Перекрёстка.');
 if(product&&!/^\/(?:product|products|cat\/\d+\/p)\//.test(u.pathname))throw Error('Вставьте ссылку на карточку товара, а не на поиск или главную страницу.');
 u.hash='';return{url:u.href,store:entry[0]};
}
function decodeNuxt(html){const m=html.match(/<script\b[^>]*\bid="__NUXT_DATA__"[^>]*>([\s\S]*?)<\/script>/);if(!m)return null;const a=JSON.parse(m[1]);if(!Array.isArray(a)||a.length>150000)throw Error('Неизвестный формат данных магазина.');const memo=new Map();
 function read(i,depth=0){if(depth>120)throw Error('Слишком сложная структура каталога.');if(i===-1)return undefined;if(i===-2)return NaN;if(!Number.isInteger(i)||i<0||i>=a.length)return null;if(memo.has(i))return memo.get(i);const v=a[i];if(v===null||typeof v!=='object')return v;
 if(Array.isArray(v)&&typeof v[0]==='string'){if(['Reactive','ShallowReactive','Ref','ShallowRef'].includes(v[0]))return read(v[1],depth+1);if(v[0]==='EmptyRef'||v[0]==='EmptyShallowRef')return null;if(v[0]==='Set')return [];throw Error('Неподдерживаемый тип данных магазина.');}
 const out=Array.isArray(v)?[]:Object.create(null);memo.set(i,out);for(const[k,n]of Object.entries(v)){if(['__proto__','constructor','prototype'].includes(k))continue;out[k]=read(n,depth+1)}return out;
 }return read(0);
}
function assess(p){const issues=[];if(!(p.priceRub>0))issues.push('Нет цены упаковки');if(!(p.packGrams>0))issues.push('Нет подтверждённой массы в граммах');if(!(Number.isFinite(p.kcal100g)&&p.kcal100g>=0&&p.kcal100g<=1000))issues.push('Нет калорийности на 100 г');if(p.available!==true)issues.push('Наличие не подтверждено');if(!p.regionVerified)issues.push('Цена для Воронежа не подтверждена');if(p.priceKind!=='regular')issues.push('Цена требует проверки условий');p.issues=issues;p.usable=issues.length===0;return p}
function magnit(html,url,city){const n=decodeNuxt(html);if(!n)return null;const id=new URL(url).pathname.split('/')[2]?.split('-')[0];const entries=Object.entries(n.data||{}).filter(([key,value])=>key.startsWith('goods-detail:')&&value&&String(value.id)===id);if(entries.length!==1)return null;const p=entries[0][1],store=n.pinia?.stores?.selectedStoreRef;
 const params=(p.details||[]).flatMap(x=>x.parameters||[]),get=name=>params.find(x=>x.name===name)?.value;
 const nutrition=(p.details||[]).find(x=>x.type==='nutritionFactsType'&&/100\s*(грамм|г\b)/i.test(x.name||''));const nutrient=name=>number(nutrition?.parameters?.find(x=>x.name===name)?.value);
 const kg=number(get('Вес, кг')),g=number(get('Вес, г')),weighted=p.weighted?.isWeighted===true;
 const actualCode=String(p.storeCode||''),address=plain(store?.address);const requestedCode=new URL(url).searchParams.get('shopCode');
 const verified=Boolean(actualCode&&store?.externalId?.storeCode===actualCode&&cityInAddress(address,city)&&(!requestedCode||requestedCode===actualCode));
 let source=url;try{const v=validateURL(p.pageUrl);if(v.store==='magnit')source=v.url}catch{}
 const result={externalId:String(p.id),name:plain(p.name),priceRub:number(p.price)===null?null:p.price/100,packGrams:weighted?null:g??(kg===null?null:kg*1000),packLabel:weighted?'Весовой товар: нужно проверить единицу цены':kg!==null?`${kg*1000} г`:g!==null?`${g} г`:plain(get('Объем, л')||get('Объём, л'))||'Масса не указана',kcal100g:nutrient('Ккал'),protein100g:nutrient('Белки'),fat100g:nutrient('Жиры'),carbs100g:nutrient('Углеводы'),ingredients:plain((p.details||[]).find(x=>x.name==='Состав')?.value),available:p.isMissing===false&&number(p.quantity)>0,priceKind:'regular',storeCode:actualCode,storeAddress:address,regionVerified:verified,sourceUrl:source,requestedUrl:url,regionNote:verified?'Магазин в Воронеже подтверждён':`Фактическая точка: ${address||'не указана'}. Код ${actualCode||'не указан'}. В расчёт для Воронежа не включаем.`};
 if(weighted)result.priceKind='weighted';return assess(result);
}
function gramQuantity(v){if(!v)return null;if(typeof v==='object'){const n=number(v.value),unit=String(v.unitCode||v.unitText||'').toLowerCase();if(n===null)return null;if(['grm','g','г','грамм'].includes(unit))return n;if(['kgm','kg','кг'].includes(unit))return n*1000;return null}const m=String(v).match(/^\s*(\d+(?:[.,]\d+)?)\s*(кг|г|kg|g)\s*$/i);return m?number(m[1])*(/^(кг|kg)$/i.test(m[2])?1000:1):null}
function jsonLD(html,url,requestedCity){const nodes=[];for(const match of html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const x=JSON.parse(match[1]);const visit=v=>{if(Array.isArray(v))v.forEach(visit);else if(v&&typeof v==='object'){nodes.push(v);if(v['@graph'])visit(v['@graph'])}};visit(x)}catch{}}
 const candidates=nodes.filter(p=>p['@type']==='Product'||Array.isArray(p['@type'])&&p['@type'].includes('Product'));if(candidates.length!==1)return null;const p=candidates[0],offers=Array.isArray(p.offers)?p.offers:[p.offers];if(offers.length!==1||!offers[0])return null;const o=offers[0],nutrition=p.nutrition||{},address=o.availableAtOrFrom?.address||o.seller?.address||{},city=plain(address.addressLocality);
 const serving=gramQuantity(nutrition.servingSize),cal=typeof nutrition.calories==='string'?nutrition.calories.match(/^(\d+(?:[.,]\d+)?)\s*(?:kcal|ккал)$/i):null;
 return assess({externalId:plain(String(p.sku||p.productID||'')),name:plain(p.name),priceRub:o.priceCurrency==='RUB'?number(o.price):null,packGrams:gramQuantity(p.weight),packLabel:gramQuantity(p.weight)?`${gramQuantity(p.weight)} г`:'Масса не указана',kcal100g:serving===100&&cal?number(cal[1]):null,protein100g:null,fat100g:null,carbs100g:null,ingredients:'',available:/(?:^|\/)InStock$/.test(o.availability||''),priceKind:'unverified',storeCode:plain(o.availableAtOrFrom?.branchCode),storeAddress:[city,plain(address.streetAddress)].filter(Boolean).join(', '),regionVerified:city.toLowerCase()===requestedCity.toLowerCase(),regionNote:'Регион и условия цены требуют проверки по данным магазина.',sourceUrl:url,requestedUrl:url});
}
function parseProduct(html,url,city='Воронеж'){const {store}=validateURL(url);if(/js-challenge-loader|servicepipe\.tech|captcha|access denied|доступ ограничен/i.test(html)&&!html.includes('__NUXT_DATA__'))throw Error('Магазин требует проверку браузера или ограничил автоматическую загрузку.');const p=store==='magnit'?magnit(html,url,city):jsonLD(html,url,city);if(!p?.name)throw Error('Карточка не содержит доступных структурированных данных. Для этого источника нужен доступ к каталогу/API магазина.');p.issues=p.issues.map(x=>x.replace('Цена для Воронежа не подтверждена','Город цены не подтверждён: '+city));return{...p,store,city,fetchedAt:new Date().toISOString(),parser:store==='magnit'?'magnit-nuxt-v1':'schema-product-v1'};}
function cityInAddress(address,city){const a=address.toLowerCase().replace(/ё/g,'е').split(/[,;]/).map(x=>x.trim().replace(/^г\.?\s+|\s+г\.?$/g,''));return a.includes(city.toLowerCase().replace(/ё/g,'е'))}
module.exports={STORES,validateURL,decodeNuxt,parseProduct,number,gramQuantity,assess};
